### ISSUE TITLE
raise RuntimeError( RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()

### ISSUE THREAD

**Issue by shibisuriya** [ranjanrak/async-ticker#1]
The script doesn't work out of the box on python3, 
Stack trace... 

shibisuriya@Shibis-MacBook-Air Kite-Connect-API % python3 asyncio_ticker.py 
Traceback (most recent call last):
  File "asyncio_ticker.py", line 6, in <module>
    from autobahn.asyncio.websocket import WebSocketClientProtocol, WebSocketClientFactory
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/autobahn/asyncio/__init__.py", line 32, in <module>
    from autobahn.asyncio.websocket import \
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/autobahn/asyncio/websocket.py", line 36, in <module>
    from autobahn.wamp import websocket
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/autobahn/wamp/websocket.py", line 32, in <module>
    from autobahn.websocket import protocol
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/autobahn/websocket/protocol.py", line 2533, in <module>
    class WebSocketServerProtocol(WebSocketProtocol):
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/autobahn/websocket/protocol.py", line 2538, in WebSocketServerProtocol
    log = txaio.make_logger()
  File "/Users/shibisuriya/Library/Python/3.8/lib/python/site-packages/txaio/_unframework.py", line 41, in _throw_usage_error
    raise RuntimeError(
RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()

**Comment by ranjanrak** [comment]
Working fine on Python 3.8.10.
> RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()

Something to do with txaio, you have added at your end? 
You would need to set `txaio.use_asyncio()`

**Comment by shibisuriya** [comment]
Hi Rakesh, Thank you for replying, can please add the requirements.txt, so that I can install appropriate version of the required python modules (dependencies) so that this error goes away?
