### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by kimblylabs** [ranjanrak/async-ticker#3]
In [2]: ws.connect_ws()
Traceback (most recent call last):

  File "/var/folders/sv/lqk08_090jj5sffd57rb2hxm0000gp/T/ipykernel_81562/139814159.py", line 1, in <module>
    ws.connect_ws()

  File "/Users/satya2/Desktop/Algo Projects/Satya Projects/async-ticker/async_ticker.py", line 103, in connect_ws
    loop.run_until_complete(coro)

  File "/Users/satya2/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()

  File "/Users/satya2/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 583, in _check_running
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running

**Comment by kimblylabs** [comment]
I think this is happening when I run the code in Spyder with Anaconda Navigator. It works fine in the terminal.
